### ISSUE TITLE
[i18n]: seems some paragraph missing from src

### ISSUE THREAD

**Issue by seognil** [StateOfJS/State-of-JS-2019#51]
e.g.

> Destructuring 
> The destructuring assignment syntax is a JavaScript expression that makes it possible to unpack values from arrays, or properties from objects, into distinct variables.

can't find it for translation

**Comment by impodracer** [comment]
It looks like those descriptions in 'Features' crawls the definition of MDN except Decorator. I think there's a way to crawl definition depending on current language which I do not know.

**Comment by SachaG** [comment]
Oh right. Currently we get those descriptions through our own API which makes it a little harder to get the correct language. I think for now we can leave them in English, or maybe just hide them?

**Comment by arcdelta** [comment]
Faced this issue as well. The absence of blocks `block.description.proxies`, `block.description.async_await` and `block.description.promises` in locale file leads to displaying descriptions like on the screenshot.

![image](https://user-images.githubusercontent.com/9627331/72425082-e4bf5800-37a8-11ea-9dc7-8cda6fd78646.png)

For now, I added these blocks into our locale yml for consistency of translation. @SachaG is this ok, at least as a temporary solution?

```yaml
# The descriptions for these blocks are loaded from the StateOfJS API,
# which causes them to be untranslated, so for now defining them here
# for consistency

- key: block.description.proxies
  t: >
    ... [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

- key: block.description.async_await
  t: >
    ... [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

- key: block.description.promises
    ... [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
```
